import os
from dotenv import load_dotenv

load_dotenv()

class Config:
    BOT_TOKEN = os.getenv("BOT_TOKEN")
    SEATABLE_SERVER = os.getenv("SEATABLE_SERVER")

    SEATABLE_API_APP_TOKEN = os.getenv("SEATABLE_API_APP_TOKEN")
    SEATABLE_MAIN_MENU_EMPLOYEE_ID = os.getenv("SEATABLE_MAIN_MENU_EMPLOYEE_ID")
    SEATABLE_MAIN_MENU_NEWCOMER_ID = os.getenv("SEATABLE_MAIN_MENU_NEWCOMER_ID")
    BROADCAST_TABLE_ID = os.getenv("BROADCAST_TABLE_ID")

    SEATABLE_API_USER_TOKEN = os.getenv("SEATABLE_API_USER_TOKEN")
    SEATABLE_1C_TABLE_ID = os.getenv("SEATABLE_1C_TABLE_ID")
    SEATABLE_ATS_BOOK_ID = os.getenv("SEATABLE_ATS_BOOK_ID")
    SEATABLE_SHOP_TABLE_ID = os.getenv("SEATABLE_SHOP_TABLE_ID")
    SEATABLE_DRUGSTORE_TABLE_ID = os.getenv("SEATABLE_DRUGSTORE_TABLE_ID")
    SEATABLE_PIVOT_TABLE_ID = os.getenv("SEATABLE_PIVOT_TABLE_ID")
    SEATABLE_USERS_TABLE_ID = os.getenv("SEATABLE_USERS_TABLE_ID")
    SEATABLE_ADMIN_TABLE_ID = os.getenv("SEATABLE_ADMIN_TABLE_ID")

    SEATABLE_API_PULSE_TOKEN = os.getenv("SEATABLE_API_PULSE_TOKEN")
    SEATABLE_PULSE_TASKS_ID = os.getenv("SEATABLE_PULSE_TASKS_ID")
    SEATABLE_PULSE_CONTENT_ID = os.getenv("SEATABLE_PULSE_CONTENT_ID")



